% imports OE xml file containing the signal chain settings. Input
% settings.xml file and desired lines (not necessary) to obtain table of
% the OE signal chain.

function settingstab = import_OE_SignalChain(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SETTINGS2 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  SETTINGS2 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  settings2 = importfile("Z:\projmon\ericsprojects\dPAL\EPHYSDATA\DF17\examplesignal_rawlfp_121923\Record Node 101\settings.xml", [2, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 18-Jan-2024 12:32:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "xmlVersion10EncodingUTF8";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "xmlVersion10EncodingUTF8", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "xmlVersion10EncodingUTF8", "EmptyFieldRule", "auto");

% Import the data
settings = readmatrix(filename, opts);

OE_VerIdx = find(contains(settings,'version','IgnoreCase',1));
verName =  extractBetween(settings(OE_VerIdx(1)),'>','<');

% Open Ephys changed how the settings file is handled in V5/V6
switch verName{1}(1:3)
    case '0.5'
        OE_Version = 5;
        nodeStr = 'NodeId';
    case '0.6'
        OE_Version = 6;
        nodeStr = 'nodeId';
    otherwise
        error('Unknown OE Version')
end

NodeIdx=contains(settings,nodeStr);

PluginIdx=contains(settings,'pluginName');

%% 

plugin=settings(PluginIdx);
node=settings(NodeIdx);

pluginName=extractAfter(plugin,'pluginName=');
pluginName=extractBetween(pluginName,'"','"');

nodeName=extractAfter(node,[nodeStr,'=']);
nodeName=extractBetween(nodeName,'"','"');

settingstab=table(nodeName,pluginName);



end